name: CI/CD Deploy DaiVietKyNhan FE

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: daivietkynhan/daivietkynhan-fe

jobs:
  # Job 1: Build và đẩy image lên Docker Hub (AN TOÀN)
  build_and_push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:latest

  # Job 2: Triển khai lên VPS
  deploy:
    name: Deploy to VPS
    needs: build_and_push
    runs-on: ubuntu-latest
    # Kết nối với môi trường 'production' để lấy secrets
    environment:
      name: production

    steps:
      # Dùng action chuyên dụng để cài đặt SSH key, an toàn hơn
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: 'just-a-placeholder'

      # Thêm IP của VPS vào danh sách các host đã biết
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # SSH vào VPS và chạy các lệnh deploy bạn muốn
      - name: Deploy using Docker Compose
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            mkdir -p /home/root/FE && cd /home/root/FE

            echo "${{ secrets.ENV_FILE_PRODUCTION }}" > .env

            echo "${{ secrets.COMPOSE_FILE_PRODUCTION }}" > docker-compose.yml

            docker-compose down

            docker-compose pull

            docker-compose up -d

            docker image prune -af
          EOF